apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: part-inventory-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: part-inventory-service
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  behavior:
      scaleUp:
        stabilizationWindowSeconds: 120    # wait 120s before scaling up again
        policies:
          - type: Percent
            value: 100                    # can double replicas per step
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300   # wait 5 min before scaling down
        policies:
          - type: Pods
            value: 1                      # remove at most 1 pod per 60s
            periodSeconds: 60