apiVersion: apps/v1
kind: Deployment
metadata:
  name: part-order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: part-order-service
  template:
    metadata:
      labels:
        app: part-order-service
    spec:
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "hdd"
          effect: "NoSchedule"
        - key: "type"
          operator: "Equal"
          value: "ssd"
          effect: "NoSchedule"
#      affinity:
#        podAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                      - part-inventory-service
#              topologyKey: kubernetes.io/hostname
      containers:
        - name: part-order-service
          image: ram1uj/part-order-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: INVENTORY_SERVICE_URL
              value: "http://part-inventory-service"
          ports:
            - containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            failureThreshold: 3
#
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 10
#            failureThreshold: 3
#            timeoutSeconds: 5
#
#          startupProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8080
#            initialDelaySeconds: 60
#            periodSeconds: 10
#            failureThreshold: 3
#            timeoutSeconds: 5


#      initContainers:
#        - name: wait-for-inventory-service
#          image: busybox
#          command:
#            - sh
#            - -c
#            - |
#              until nc -z -v -w30 part-inventory-service 80; do
#                echo "Waiting for part-inventory-service to be available..."
#                sleep 5
#              done
